name: sub-qwatt-env-001
concurrency: sub-qwatt-env-001

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify the tag of the deployment.'
        required: false
        type: string
      environment:
        options:
            - dev
            - test
            - stage
            - prod
        type: choice


jobs:
  validate-bicep-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        if: github.event.inputs.environment == 'prod' && github.ref == 'refs/heads/main' && (github.event.inputs.tag == 'sub/' || github.event.inputs.tag == 'rg/')
